silk-framework/silk

silk-core/src/main/scala/org/silkframework/rule/RuleTraverser.scala
silk-workbench/silk-workbench-rules/app/views/editor/renderRule.scala.html

`val block = (value - minValue) * blockCount` would work only for normalized values (with min=0 and max=1)
for other values, a normalization over the values interval is necessary.

 	Update continuous index in Index.scala

---

.gitignore
build.sbt
silk-tools/silk-mapreduce/build.sbt
silk-tools/silk-mapreduce/src/main/scala/org/silkframework/hadoop/Load.scala
silk-tools/silk-mapreduce/src/main/scala/org/silkframework/hadoop/Match.scala
silk-tools/silk-mapreduce/src/main/scala/org/silkframework/hadoop/SilkConfiguration.scala
silk-tools/silk-mapreduce/src/main/scala/org/silkframework/hadoop/impl/HadoopEntityCache.scala
silk-tools/silk-mapreduce/src/main/scala/org/silkframework/hadoop/impl/SilkInputFormat.scala
silk-tools/silk-mapreduce/src/main/scala/org/silkframework/hadoop/impl/SilkMap.scala
silk-tools/silk-mapreduce/src/main/scala/org/silkframework/hadoop/impl/SilkOutputFormat.scala
silk-tools/silk-mapreduce/src/main/scala/org/silkframework/hadoop/impl/SilkReduce.scala

This is an upgraded version of Silk MapReduce which can compile against the current version of Silk Core.
Build files have also been updated to be able to generate an assembly JAR.
This should fix #41.

Silk Mapreduce Upgrade

---

silk-plugins/silk-plugins-rdf/src/main/scala/org/silkframework/plugins/dataset/rdf/sparql/SimpleEntityRetriever.scala

In SimpleEntityRetriever the original sparql SELECT statement was wrapped by
another SELECT query to solve a paging problem with ORDER BY clause.
The problem occurs in a Virtuoso remote endpoint. This commit fixes #31

Fixed paging problem within SimpleEntityRetriever

---

silk-core/src/main/scala/org/silkframework/util/Table.scala

- correct multilines (backslash instead of pipe for new line)
- hyphen after camel case splits
- splits after / (for long URIs)
This is part of fixing CMEM-78 (rest is in DI)

table building algorithm improved:

---

silk-react-components/src/HierarchicalMapping/store.js
silk-workbench/silk-workbench-core/public/libs/silk-react-components/main.js

The conversion to boolean was done twice. Look at the ObjectMappingRuleForm for verification see 
https://github.com/silk-framework/silk/blob/develop/silk-react-components/src/HierarchicalMapping/Components/MappingRule/Forms/ObjectMappingRuleForm.jsx#L143

fix parameter isBackwardProperty: 

---

silk-core/src/main/scala/org/silkframework/execution/AbortExecutionException.scala
silk-core/src/main/scala/org/silkframework/execution/ExecutionException.scala
silk-rules/src/main/scala/org/silkframework/rule/execution/ExecuteTransform.scala
silk-rules/src/main/scala/org/silkframework/rule/execution/local/TransformedEntities.scala
silk-workspace/src/main/scala/org/silkframework/workspace/activity/linking/ExecuteLinkingFactory.scala

Introduces AbortExecutionException that aborts execution of the task if thrown inside a transform operator.

Introduce AbortExecutionException

---

Dockerfile

docker container built from source does not run properly. It exits with Docker error (255) equivalent to bash -1 error code. The reason is incorrect resolution of the $PORT environment variable.

- Fix for issue #251 (fresh Docker built container not running)

---

silk-rules/src/main/scala/org/silkframework/rule/LinkageRule.scala
silk-rules/src/main/scala/org/silkframework/rule/Operator.scala
silk-rules/src/main/scala/org/silkframework/rule/TransformRule.scala
silk-rules/src/test/scala/org/silkframework/rule/TransformRuleTest.scala
silk-rules/src/test/scala/org/silkframework/rule/execution/ExecuteTransformTest.scala
silk-workbench/silk-workbench-rules/app/controllers/transform/TransformTaskApi.scala
silk-workbench/silk-workbench-rules/public/stylesheets/editor/editor.css
silk-workbench/silk-workbench-rules/test/controllers/transform/AutoCompletionApiTest.scala

Fixes two bugs:
-  The rule editors did not validate if operator identifiers are unique. Validate by giving two operators the same identifier.
- Long identifiers are now shortened in the UI. Validate by setting a very long identifier.

Rule Editor fixes

---

silk-rules/src/main/scala/org/silkframework/rule/plugins/RulePlugins.scala
silk-rules/src/main/scala/org/silkframework/rule/plugins/distance/equality/EqualityMetric.scala
silk-rules/src/main/scala/org/silkframework/rule/plugins/distance/equality/NumericEqualityMetric.scala
silk-rules/src/test/scala/org/silkframework/rule/plugins/distance/equality/EqualityMetricTest.scala
silk-rules/src/test/scala/org/silkframework/rule/plugins/distance/equality/NumericEqualityMetricTest.scala

- compares values numerically instead of the string value
- allows to set precision to allow some (usually small) difference

Feature: numeric equality operator

---

silk-react-components/package.json
silk-react-components/yarn.lock

The FAB adds a eventlistener for clicks to close the context menu. This event was never removed and raised errors in console

forward gui-elements to fix not closing click events from FAB

---

silk-core/src/main/scala/org/silkframework/runtime/activity/ActivityMonitor.scala
silk-core/src/test/scala/org/silkframework/runtime/activity/ActivityExecutionTest.scala

Maintain thread pool parallelism if many activities are blocking

Maintain thread pool parallelism if many activities are blocking

---

silk-core/src/main/scala/org/silkframework/runtime/plugin/ParameterType.scala
silk-core/src/main/scala/org/silkframework/util/AesCrypto.scala

- Using AES-256 instead of AES-128.
- If no valid key has been configured in production mode, application does not start.
- Better error messages, if key is invalid.
- Secret key is generated from the configured key using SHA1 hashing allowing for arbitrarily long keys.

Improved password encryption

---

silk-core/src/main/scala/org/silkframework/runtime/resource/InMemoryResourceManager.scala
silk-core/src/main/scala/org/silkframework/runtime/resource/ResourceWriter.scala
silk-tools/silk-singlemachine/src/main/scala/org/silkframework/Silk.scala
silk-workbench/silk-workbench-workspace/app/controllers/workspace/WorkspaceController.scala
silk-workbench/silk-workbench-workspace/app/views/workspace/removeProjectDialog.scala.html
silk-workspace/src/main/scala/org/silkframework/workspace/Workspace.scala
silk-workspace/src/main/scala/org/silkframework/workspace/resources/EmptyResourceRepository.scala
silk-workspace/src/main/scala/org/silkframework/workspace/resources/FileRepository.scala
silk-workspace/src/main/scala/org/silkframework/workspace/resources/InMemoryResourceRepository.scala
silk-workspace/src/main/scala/org/silkframework/workspace/resources/PerProjectFileRepository.scala
silk-workspace/src/main/scala/org/silkframework/workspace/resources/ResourceRepository.scala
silk-workspace/src/main/scala/org/silkframework/workspace/resources/ResourceRepositoryPlugins.scala
silk-workspace/src/main/scala/org/silkframework/workspace/resources/SharedFileRepository.scala
silk-workspace/src/test/scala/org/silkframework/workspace/TestWorkspaceProviderTestTrait.scala
silk-workspace/src/test/scala/org/silkframework/workspace/resources/InMemoryResourceRepositoryTest.scala
silk-workspace/src/test/scala/org/silkframework/workspace/resources/PerProjectFileRepositoryTest.scala
silk-workspace/src/test/scala/org/silkframework/workspace/resources/PerProjectResourceRepositoryTest.scala
silk-workspace/src/test/scala/org/silkframework/workspace/resources/ResourceRepositoryTest.scala
silk-workspace/src/test/scala/org/silkframework/workspace/resources/SharedFileRepositoryTest.scala
silk-workspace/src/test/scala/org/silkframework/workspace/resources/SharedResourceRepositoryTest.scala

- Consistent resource deletion behaviour for resource repositories:
- For resource repositories that do not share resources between projects, resources are removed on project deletion.
- For resource repositories that do share resources between projects, resources are NOT removed on project deletion.
- In both cases, the user is informed in the UI about the behaviour of the configured resource repository.

Consistent resource deletion behaviour for resource repositories

---

silk-rules/src/main/scala/org/silkframework/rule/plugins/transformer/substring/SubstringTransformer.scala
silk-rules/src/main/scala/org/silkframework/rule/similarity/Comparison.scala
silk-workbench/silk-workbench-rules/app/controllers/linking/EvaluateLinkingController.scala
silk-workbench/silk-workbench-rules/app/controllers/linking/Learning.scala
silk-workbench/silk-workbench-rules/app/views/widgets/linksTable.scala.html

- Substring transformer should generate an empty value, if an index is out of range and 'stringMustBeInRange' is false.
- If a transformer inside a linkage rule throws a validation error, it will no longer fail the entire linking task, but just not generate a link for that single entity.

Fixed linking validation errors

---

silk-core/src/main/scala/org/silkframework/runtime/resource/Resource.scala
silk-core/src/main/scala/org/silkframework/runtime/resource/ResourceTooLargeException.scala
silk-plugins/silk-plugins-json/src/main/scala/org/silkframework/plugins/dataset/json/JsonDataset.scala
silk-plugins/silk-plugins-json/src/test/scala/org/silkframework/plugins/dataset/json/JsonDatasetTest.scala
silk-plugins/silk-plugins-rdf/src/main/scala/org/silkframework/plugins/dataset/rdf/datasets/RdfFileDataset.scala
silk-plugins/silk-plugins-rdf/src/test/scala/org/silkframework/plugins/dataset/rdf/RdfFileDatasetTest.scala
silk-plugins/silk-plugins-xml/src/main/scala/org/silkframework/plugins/dataset/xml/XmlDataset.scala
silk-plugins/silk-plugins-xml/src/test/scala/org/silkframework/plugins/dataset/xml/XmlDatasetTest.scala

XML and JSON: Files larger than the configured resource maxInMemorySize are not loaded into memory returning an error instead

Fix loading large files into memory

---

silk-core/src/main/scala/org/silkframework/execution/ExecutionReport.scala
silk-core/src/main/scala/org/silkframework/execution/ExecutionReportUpdater.scala
silk-core/src/main/scala/org/silkframework/execution/SimpleExecutionReport.scala
silk-core/src/main/scala/org/silkframework/execution/local/LocalDatasetExecutor.scala
silk-plugins/silk-plugins-rdf/src/main/scala/org/silkframework/plugins/dataset/rdf/executors/LocalSparqlSelectExecutor.scala
silk-plugins/silk-plugins-rdf/src/main/scala/org/silkframework/plugins/dataset/rdf/executors/LocalSparqlUpdateExecutor.scala
silk-plugins/silk-serialization-json/src/main/scala/org/silkframework/serialization/json/ExecutionReportSerializers.scala
silk-react-components/src/ExecutionReport/ExecutionReport.jsx
silk-react-components/src/ExecutionReport/ExecutionReport.scss
silk-react-components/src/ExecutionReport/WorkflowExecutionReport.jsx
silk-react-components/src/ExecutionReport/WorkflowReportManager.jsx
silk-workbench/silk-workbench-workflow/app/controllers/workflow/WorkflowApi.scala
silk-workbench/silk-workbench-workspace/app/controllers/workspaceApi/ReportsApi.scala
silk-workspace/src/main/scala/org/silkframework/workspace/activity/workflow/WorkflowExecutionReport.scala
silk-workspace/src/main/scala/org/silkframework/workspace/activity/workflow/WorkflowExecutor.scala
silk-workspace/src/test/scala/org/silkframework/workspace/activity/workflow/LocalWorkflowExecutorTest.scala

- Improvements to execution reports (CMEM-3383)
- Added an overview section, which displays general information about the execution:
- Final workflow status
- Start, finish and cancellation times
- Users account which started and canceled (if any) the execution
- All operator executions are persisted. For instance, workflow reports will contain separate task reports for writing and reading a dataset.
- For each operator execution, an optional operation label can be shown (e.g., read, write, generate queries). 
- The order of the task reports is stable now and reflects the order of execution.
- Added a scrollbar to the task list, if it is too large to be displayed.

execution report improvements

---

silk-react-components/silk-workbench/silk-workbench-workflow/public/editor/editor.js
silk-react-components/silk-workbench/silk-workbench-workflow/public/editor/serializeWorkflow.js
silk-workbench/silk-workbench-workflow/app/views/workflow/editor/editor.scala.html

- On loading, the save button is only enabled after the workflow has been loaded to prevent the user from saving an empty workflow.
- A spinner is shown while the workflow is saved.
- The save button is disabled while the workflow is saved.
- A confirm dialog is shown, if the user tries to leave while a save is in progress.

Improve workflow saving

---

Dockerfile
README.md

- Use latest OpenJDK jre for Docker image
- Improve README regarding building the Docker image

Use latest OpenJDK 8 jre for Docker image

---

silk-core/src/main/scala/org/silkframework/config/Task.scala
silk-workspace/src/main/scala/org/silkframework/workspace/CircularDependencyException.scala
silk-workspace/src/main/scala/org/silkframework/workspace/Module.scala
silk-workspace/src/main/scala/org/silkframework/workspace/Project.scala
silk-workspace/src/main/scala/org/silkframework/workspace/ProjectTask.scala
silk-workspace/src/test/scala/org/silkframework/workspace/ProjectTaskTest.scala
silk-workspace/src/test/scala/org/silkframework/workspace/ProjectTest.scala

- Fixed infinite recursion if there are circular references in between tasks.
- Do not allow adding or updating tasks that would create a new circular dependency.

Fix dependent tasks recursion 

---

build.sbt
silk-core/src/main/scala/org/silkframework/dataset/rdf/RdfDataset.scala
silk-core/src/main/scala/org/silkframework/entity/rdf/SparqlEntitySchema.scala
silk-core/src/main/scala/org/silkframework/entity/rdf/SparqlPathBuilder.scala
silk-core/src/main/scala/org/silkframework/util/StreamUtils.scala
silk-plugins/silk-persistent-caching/src/main/scala/org/silkframework/runtime/caching/PersistentSortedKeyValueStore.scala
silk-plugins/silk-plugins-rdf/src/main/scala/org/silkframework/plugins/dataset/rdf/sparql/EntityRetriever.scala
silk-plugins/silk-plugins-rdf/src/main/scala/org/silkframework/plugins/dataset/rdf/sparql/ParallelEntityRetriever.scala
silk-plugins/silk-plugins-rdf/src/main/scala/org/silkframework/plugins/dataset/rdf/sparql/SimpleEntityRetriever.scala
silk-plugins/silk-plugins-rdf/src/test/scala/org/silkframework/plugins/dataset/rdf/sparql/SparqlPathBuilderTest.scala
silk-workbench/silk-workbench-rules/test/controllers/transform/PartialAutoCompletionApiTest.scala

- Literals can thus be mapped in object mappings
- Add special path #text to fetch the lexical value of the currently selected RDF node. This is mostly needed when mapping literals in object mappings.
- Add special path #lang to get the language tag of a language tag literal.

Allow literals as entities

---

silk-react-components/package.json
silk-react-components/yarn.lock

- Use title as default for ContextMenu to prevent interference of the menu items with the (portal based) tooltip.

Use title attribute instead of Tooltip for context menus

---

silk-plugins/silk-plugins-rdf/src/main/scala/org/silkframework/plugins/dataset/rdf/endpoint/PagingSparqlTraversable.scala
silk-plugins/silk-plugins-rdf/src/main/scala/org/silkframework/plugins/dataset/rdf/tasks/SparqlSelectCustomTask.scala
silk-plugins/silk-plugins-rdf/src/main/scala/org/silkframework/plugins/dataset/rdf/tasks/SparqlUpdateCustomTask.scala

- Do not inject FROM clause if there already exists a FROM clause in the query.
- Document FROM clause injection in SPARQL Select and Update (lack of) operators.

Document sparql select injection into SPARQL Select queries

---

silk-core/src/main/scala/org/silkframework/config/HasMetaData.scala
silk-core/src/main/scala/org/silkframework/dataset/rdf/GraphStoreTrait.scala
silk-core/src/main/scala/org/silkframework/workspace/WorkspaceProvider.scala
silk-workbench/silk-workbench-workspace/app/controllers/projectApi/ProjectApi.scala
silk-workbench/silk-workbench-workspace/test/controllers/workspace/ExportIntegrationTestTrait.scala
silk-workbench/silk-workbench-workspace/test/controllers/workspace/MockableWorkspaceProvider.scala
silk-workbench/silk-workbench-workspace/test/controllers/workspace/SearchApiIntegrationTest.scala
silk-workbench/silk-workbench-workspace/test/controllers/workspaceApi/ProjectLoadingErrorIntegrationTest.scala
silk-workspace/src/main/scala/org/silkframework/workspace/CombinedWorkspaceProvider.scala
silk-workspace/src/main/scala/org/silkframework/workspace/InMemoryWorkspaceProvider.scala
silk-workspace/src/main/scala/org/silkframework/workspace/Module.scala
silk-workspace/src/main/scala/org/silkframework/workspace/Project.scala
silk-workspace/src/main/scala/org/silkframework/workspace/Workspace.scala
silk-workspace/src/main/scala/org/silkframework/workspace/io/WorkspaceIO.scala
silk-workspace/src/main/scala/org/silkframework/workspace/xml/CustomTaskXmlSerializer.scala
silk-workspace/src/main/scala/org/silkframework/workspace/xml/DatasetXmlSerializer.scala
silk-workspace/src/main/scala/org/silkframework/workspace/xml/LinkingXmlSerializer.scala
silk-workspace/src/main/scala/org/silkframework/workspace/xml/TransformXmlSerializer.scala
silk-workspace/src/main/scala/org/silkframework/workspace/xml/WorkflowXmlSerializer.scala
silk-workspace/src/main/scala/org/silkframework/workspace/xml/XmlSerializer.scala
silk-workspace/src/main/scala/org/silkframework/workspace/xml/XmlWorkspaceProvider.scala
silk-workspace/src/test/scala/org/silkframework/workspace/WorkspaceProviderTestTrait.scala
silk-workspace/src/test/scala/org/silkframework/workspace/WorkspaceTest.scala
silk-workspace/src/test/scala/org/silkframework/workspace/xml/XmlZipProjectMarshalingTest.scala

- Added readAllTasks() to load all tasks of all types at once
- Task loading methods return an instance of LoadedTask
- Correctly use Either (the right value is supposed to hold the correct result and not vice versa)
- Use readAllTasks in Workspace to improve performance for RDF Workspaces

Improved WorkspaceProvider API

---

silk-plugins/silk-plugins-rdf/src/main/scala/org/silkframework/plugins/dataset/rdf/access/GraphStoreSink.scala
silk-plugins/silk-plugins-rdf/src/test/scala/org/silkframework/plugins/dataset/rdf/access/GraphStoreSinkTest.scala

Bugfix: If more triples than the configured graph store request size are written, a triple is dropped per request

Bugfix: If more triples than the configured graph store request size are written, a triple is dropped per request 

---

silk-core/src/main/scala/org/silkframework/runtime/activity/Status.scala
silk-core/src/test/scala/org/silkframework/util/StatusCodeTestTrait.scala
silk-workbench/silk-workbench-workflow/app/controllers/workflow/WorkflowApi.scala
silk-workbench/silk-workbench-workflow/app/controllers/workflowApi/WorkflowApi.scala
silk-workbench/silk-workbench-workflow/test/controllers/workflowApi/WorkflowApiTest.scala
silk-workbench/silk-workbench-workspace/app/controllers/workspace/ActivityApi.scala
silk-workbench/silk-workbench-workspace/test/controllers/workspace/ActivityApiTest.scala
silk-workspace/src/main/scala/org/silkframework/workspace/activity/WorkspaceActivity.scala

- Make number of concurrent activity instances configurable via 'org.silkframework.runtime.activity.concurrentExecutions'

Fix: sync. variable workflow executions accumulate activity instances

---

silk-workbench/app/controllers/Workbench.scala
workspace/src/app/store/ducks/common/initialState.ts
workspace/src/app/store/ducks/workspace/requests.ts
workspace/src/app/views/layout/Header/ExampleProjectImportMenu.tsx
workspace/src/app/views/layout/Header/Header.tsx
workspace/src/locales/manual/en.json

- Redirect to workbench project search page
- Remove legacy workspace link from user menu
- Add "load example project" action to user menu

Remove root page

---

silk-plugins/silk-serialization-json/src/main/scala/org/silkframework/serialization/json/JsonSerializers.scala
silk-rules/src/main/scala/org/silkframework/rule/TransformRule.scala
silk-rules/src/main/scala/org/silkframework/rule/evaluation/DetailedEvaluator.scala
silk-rules/src/main/scala/org/silkframework/rule/evaluation/DetailedIndexer.scala
silk-rules/src/main/scala/org/silkframework/rule/execution/TransformReport.scala
silk-rules/src/main/scala/org/silkframework/rule/execution/TransformReportBuilder.scala
silk-rules/src/main/scala/org/silkframework/rule/execution/local/TransformedEntities.scala
silk-rules/src/main/scala/org/silkframework/rule/input/Input.scala
silk-rules/src/main/scala/org/silkframework/rule/input/PathInput.scala
silk-rules/src/main/scala/org/silkframework/rule/input/TransformInput.scala
silk-rules/src/main/scala/org/silkframework/rule/input/Value.scala
silk-rules/src/main/scala/org/silkframework/rule/plugins/transformer/validation/ValidateRegex.scala
silk-rules/src/main/scala/org/silkframework/rule/similarity/Comparison.scala
silk-rules/src/test/scala/org/silkframework/rule/TransformRuleTest.scala
silk-rules/src/test/scala/org/silkframework/rule/execution/ExecuteTransformTest.scala
silk-rules/src/test/scala/org/silkframework/rule/similarity/ComparisonTest.scala
silk-workbench/silk-workbench-rules/app/controllers/transform/PeakTransformApi.scala
silk-workbench/silk-workbench-rules/test/controllers/transform/PeakTransformApiTest.scala
silk-workspace/src/test/scala/org/silkframework/workspace/WorkspaceProviderTestTrait.scala

The handling of errors in transform rules has been aligned with what is already shown in the evaluation (CMEM-5130)
- If a nested operator throws a validation error (e.g., if the input value is not a number for numeric operators), this no longer leads to a failure of the entire rule.
- The error will be added to the execution report.
- Failed operators will return no value.

Consistent transform errors

---

silk-core/src/main/scala/org/silkframework/workspace/WorkspaceProvider.scala
silk-workbench/silk-workbench-workspace/app/controllers/projectApi/ProjectApi.scala
silk-workbench/silk-workbench-workspace/app/controllers/workspace/WorkspaceApi.scala
silk-workbench/silk-workbench-workspace/app/controllers/workspaceApi/project/ProjectLoadingErrors.scala

- Fixed: Reloaded failed tasks are missing the original label and description

Reload failed tasks after project/workspace reload

---

workspace/src/app/views/shared/TaskConfig/TaskConfigPreview.tsx
workspace/src/app/views/taskViews/shared/rules/rule.utils.tsx

- This can happen when e.g. a Python plugin has been updated at runtime and added a new parameter. In this case the new parameter is currently missing in existing instances of that plugin.

Fix issues when updating a plugin spec at runtime

---

.gitignore
build.sbt
silk-core/src/main/resources/reference.conf
silk-core/src/main/scala/org/silkframework/config/TaskSpec.scala
silk-core/src/main/scala/org/silkframework/dataset/DataSource.scala
silk-core/src/main/scala/org/silkframework/runtime/activity/ActivityExecution.scala
silk-core/src/main/scala/org/silkframework/runtime/metrics/MeterRegistryProvider.scala
silk-core/src/main/scala/org/silkframework/runtime/metrics/MetricsConfig.scala
silk-core/src/main/scala/org/silkframework/runtime/metrics/NoopMeterRegistry.scala
silk-core/src/main/scala/org/silkframework/runtime/plugin/PluginRegistry.scala
silk-workbench/silk-workbench-core/app/config/WorkbenchConfig.scala
silk-workspace/src/main/scala/org/silkframework/workspace/Project.scala
silk-workspace/src/main/scala/org/silkframework/workspace/Workspace.scala
silk-workspace/src/main/scala/org/silkframework/workspace/activity/TaskActivity.scala
silk-workspace/src/main/scala/org/silkframework/workspace/activity/workflow/LocalWorkflowExecutor.scala
silk-workspace/src/main/scala/org/silkframework/workspace/metrics/WorkspaceMetrics.scala
silk-workspace/src/test/scala/org/silkframework/workspace/TestWorkspaceProviderTestTrait.scala
silk-workspace/src/test/scala/org/silkframework/workspace/WorkspaceProviderTestTrait.scala

This PR adds support for exposing metrics using Micrometer, with the specific use-case of Prometheus in mind.
The main changes in this PR are:
1. Integrating the **functionality of Micrometer-based metrics** and configuring the Micrometer-based metrics to work with Prometheus as the monitoring and alerting software system
2. Exposing the **thread pool metrics** of the `Activity`
3. Exposing the **total number** of **projects** and **tasks** in a **workspace**
4. Exposing the number of **tasks** by their **specification** (Transform, Dataset, Linking, Task, Workflow).
5. Exposing the **runtime** of a **workflow**, **operator** and **dataset**, as well as the **number of entities** of a dataset.
6. Exposing the **version** (Workbench Core).
7. Add the **app name** as a metrics tag, via the …

Expose metrics for Prometheus using Micrometer

---

.gitignore
silk-plugins/silk-plugins-csv/src/main/scala/org/silkframework/plugins/dataset/csv/CSVSanitizer.scala
silk-plugins/silk-plugins-csv/src/main/scala/org/silkframework/plugins/dataset/csv/CsvParser.scala
silk-plugins/silk-plugins-csv/src/main/scala/org/silkframework/plugins/dataset/csv/CsvWriter.scala
silk-plugins/silk-plugins-csv/src/test/scala/org/silkframework/plugins/dataset/csv/CSVSanitizerTest.scala

**Bugfix: CSV Injection**
This PR adds a **sanitizer** for CSV rows. It deals with the causes for CSV Injection, as documented in https://owasp.org/www-community/attacks/CSV_Injection.
The `CsvParser` from [Univocity](https://github.com/uniVocity/univocity-parsers) can't be extended (it's `final`) in a "sanitizing subclass of CsvParser", so the solution simply maps over the **cells** and converts them explicitly.

Bugfix: CSV injection

---

silk-core/src/main/scala/org/silkframework/config/InvalidConfigException.scala
silk-core/src/main/scala/org/silkframework/runtime/plugin/PluginDescription.scala
silk-core/src/main/scala/org/silkframework/runtime/plugin/types/TemplateParameter.scala
silk-core/src/main/scala/org/silkframework/runtime/templating/GlobalTemplateVariablesConfig.scala
silk-core/src/main/scala/org/silkframework/runtime/templating/TemplateVariables.scala
silk-core/src/test/scala/org/silkframework/runtime/templating/GlobalTemplateVariablesTest.scala
silk-plugins/silk-serialization-json/src/main/scala/org/silkframework/serialization/json/PluginSerializers.scala
silk-workbench/silk-workbench-core/app/controllers/workspaceApi/coreApi/VariableTemplateApi.scala
silk-workbench/silk-workbench-core/app/controllers/workspaceApi/coreApi/variableTemplate/VariableTemplateRequests.scala
silk-workbench/silk-workbench-core/app/org/silkframework/runtime/templating/operations/DeleteVariableModification.scala
silk-workbench/silk-workbench-core/app/org/silkframework/runtime/templating/operations/Modification.scala
silk-workbench/silk-workbench-core/app/org/silkframework/runtime/templating/operations/UpdateVariableModification.scala
silk-workbench/silk-workbench-core/app/org/silkframework/runtime/templating/operations/UpdateVariablesModification.scala
silk-workbench/silk-workbench-workspace/app/controllers/projectApi/requests/ReloadFailedTaskRequest.scala
silk-workspace/src/test/scala/org/silkframework/workspace/WorkspaceProviderTestTrait.scala
workspace/src/app/views/shared/modals/CreateArtefactModal/ArtefactForms/ArtefactFormParameter.tsx
workspace/src/app/views/shared/modals/CreateArtefactModal/CreateArtefactModal.requests.ts

* Sensitive variables can only be used in password fields.
* Using sensitive variables in other fields or in variable templates fails and does not expose the value.
* Example:
```
config.variables = {
global = {
sensitiveVar = {
value = "value 2"
isSensitive = true
}
}
```

Global variables can be marked sensitive for storing passwords (CMEM-4817)

---

silk-core/src/main/scala/org/silkframework/entity/rdf/SparqlRestriction.scala
silk-core/src/test/scala/org/silkframework/entity/rdf/SparqlRestrictionTest.scala
silk-workspace/src/test/scala/org/silkframework/workspace/TestWorkspaceProviderTestTrait.scala

SPARQL restriction expands wrong SPARQL pattern when using property paths with prefixed names (CMEM-6418).

Fix: SPARQL restriction expands wrong SPARQL pattern 
