silk-workbench/silk-workbench-rules/app/views/editor/transformEditor.scala.html, silk-workbench/silk-workbench-rules/public/js/editor/serializeRule.js
(cannot currently be edited in editor)
=> target type now shown and serialised in transformation editor

doc/Readme.md
+ updated README, including REST API link
+ moved linking and REST under the workspace section
=> updated README, including REST API link

silk-react-components/src/HierarchicalMapping/Components/MappingRule/Forms/ObjectMappingRuleForm.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/Forms/ValueMappingRuleForm.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/MappingRule.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/ObjectMappingRule.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/ValueMappingRule.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRuleOverview.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRuleOverviewHeader.jsx, silk-react-components/src/HierarchicalMapping/Components/TreeView.jsx, silk-react-components/src/HierarchicalMapping/HierarchicalMapping.jsx, silk-react-components/src/HierarchicalMapping/store.js
update the components communication to let know each element if there are pending changes. add dialogs to let the user know about these changes
=> add dialog for discard changes on the hierarchical mapping view

silk-react-components/src/HierarchicalMapping/Components/MappingRule/Forms/FormSaveError.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/Forms/ObjectMappingRuleForm.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/Forms/ValueMappingRuleForm.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/ObjectMappingRule.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/ValueMappingRule.jsx, silk-react-components/src/HierarchicalMapping/store.js
- Allow entering of plain URIs
- Add error handling on create / update
- Integrate external rule editor
- allows multiple target types
=> Finalize CRUD Operations

silk-react-components/src/HierarchicalMapping/Components/MappingRule/ExampleView.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/Forms/ObjectMappingRuleForm.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/Forms/ValueMappingRuleForm.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/ObjectMappingRule.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/ValueMappingRule.jsx, silk-react-components/src/HierarchicalMapping/HierarchicalMapping.scss, silk-react-components/src/HierarchicalMapping/store.js, silk-react-components/src/SilkStore/transform/transform.js, silk-workbench/silk-workbench-core/public/libs/silk-react-components/main.js
- create new component ExampleView
- added (whenever an id is available) to both value and object rule
- fix event propagation minor warning
- implemented the api call according to [DI Dokumentation](https://docs.eccenca.com/docs/develop/eccenca-DataIntegration/v3.4.0-160-g5e5773fe-dirty/eccenca-DataIntegration_v3.4.0-160-g5e5773fe-dirty_css-rel_DeveloperManual.html#transformtasksprojecttransformationtaskpeakrule)
=> added example view widget and api call

silk-react-components/package.json, silk-react-components/src/HierarchicalMapping/Components/MappingRule/Forms/AutoComplete.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/Forms/ObjectMappingRuleForm.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/Forms/ValueMappingRuleForm.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/MappingRule.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/ObjectMappingRule.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRuleOverview.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRuleOverviewHeader.jsx, silk-react-components/src/HierarchicalMapping/HierarchicalMapping.jsx, silk-react-components/src/HierarchicalMapping/store.js, silk-react-components/src/SilkStore/transform/transform.js, silk-react-components/yarn.lock
This PR introduces auto completion for
- value path
- target entity type
- target properties
=> Auto completion

silk-react-components/src/HierarchicalMapping/Components/MappingRule/ExampleView.jsx, silk-react-components/src/HierarchicalMapping/HierarchicalMapping.scss
Depends on currently unreleased GUI elements component. It needs to be released first and upgraded here.
=> add toggler to long error messages from example api

silk-react-components/src/HierarchicalMapping/Components/MappingRule/Forms/ObjectMappingRuleForm.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/SharedComponents.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/SuggestionOverview.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/SuggestionView.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/ValueMappingRule.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRuleOverview.jsx, silk-react-components/src/HierarchicalMapping/store.js
It fixes CMEM-471, CMEM-469 and CMEM-474
=> Hierarchical Mapping, minor fixes.

silk-react-components/silk-workbench/silk-workbench-rules/public/js/links.js, silk-workbench/silk-workbench-rules/public/js/links.js
fixed: changing page with pagination will reset the page to first one.
=> fix switch page with pagination

silk-react-components/src/HierarchicalMapping/Components/MappingRule/ErrorView.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/ExampleView.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/Forms/ObjectMappingRuleForm.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/Forms/ValueMappingRuleForm.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/ValueMappingRule.jsx, silk-react-components/src/HierarchicalMapping/Components/SuggestionsList.jsx, silk-react-components/src/HierarchicalMapping/store.js, silk-react-components/src/SilkStore/transform/transform.js, silk-react-components/src/style/style.scss, silk-workbench/silk-workbench-core/public/libs/silk-react-components/main.js, silk-workbench/silk-workbench-core/public/libs/silk-react-components/style.css
fixes CMEM-737, CMEM-739 and therefore CMEM-681 and CMEM-717.
=> show error messages in HM according to the new http problems representation

silk-react-components/src/HierarchicalMapping/Components/MappingRule/MappingRule.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingsHeader.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingsTree.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingsWorkview.jsx, silk-react-components/src/HierarchicalMapping/HierarchicalMapping.jsx, silk-react-components/src/HierarchicalMapping/Mixins/Navigation.js
just a few changes / removes to avoid the handleNavigation being too complex / buggy
=> wip: Fix hm tree navigation

silk-react-components/src/HierarchicalMapping/Components/MappingRule/MappingRule.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingsList.jsx, silk-react-components/src/HierarchicalMapping/store.js, silk-react-components/src/SilkStore/transform/transform.js, silk-workbench/silk-workbench-core/public/libs/silk-react-components/main.js
that mr fixes the following known issues:
- simplify the code greatly with functional style 
- use the reorder endpoint of DI
- pass the correct value of currentRuleId to the MappingList
- use messageBus for sharing order function between MappingRule and MappingList, avoiding duplicated code or complicated props pipelining.
=> fix reorder rules

silk-react-components/src/HierarchicalMapping/Components/MappingRule/Forms/ObjectMappingRuleForm.jsx, silk-react-components/src/HierarchicalMapping/Components/MappingRule/Forms/ValueMappingRuleForm.jsx, silk-workbench/silk-workbench-core/public/libs/silk-react-components/main.js
prevent 'trim() of undefined' error
=> check if properties are not undefined before trim them

silk-plugins/silk-serialization-json/src/main/scala/org/silkframework/serialization/json/EntitySerializers.scala, silk-plugins/silk-serialization-json/src/main/scala/org/silkframework/serialization/json/JsonPluginModule.scala
=> Merging CMEM 1449

silk-rules/src/main/scala/org/silkframework/rule/plugins/RulePlugins.scala, silk-rules/src/main/scala/org/silkframework/rule/plugins/distance/equality/GreaterThanMetric.scala, silk-rules/src/main/scala/org/silkframework/rule/plugins/distance/equality/LowerThanMetric.scala, silk-rules/src/test/scala/org/silkframework/rule/plugins/distance/equality/GreaterThanMetricTest.scala, silk-rules/src/test/scala/org/silkframework/rule/plugins/distance/equality/LowerThanMetricTest.scala
=> Add GreaterThanMetric

silk-core/src/main/scala/org/silkframework/dataset/DatasetSpec.scala, silk-core/src/main/scala/org/silkframework/runtime/activity/Activity.scala, silk-core/src/main/scala/org/silkframework/runtime/activity/ActivityExecution.scala, silk-core/src/main/scala/org/silkframework/runtime/activity/ActivityMonitor.scala, silk-core/src/main/scala/org/silkframework/runtime/activity/StatusHolder.scala, silk-core/src/main/scala/org/silkframework/runtime/activity/UserContext.scala, silk-core/src/main/scala/org/silkframework/runtime/users/User.scala, silk-core/src/test/scala/org/silkframework/runtime/activity/ActivityExecutionTest.scala, silk-plugins/silk-plugins-rdf/src/main/scala/org/silkframework/plugins/dataset/rdf/access/GraphStoreSink.scala, silk-plugins/silk-plugins-rdf/src/main/scala/org/silkframework/plugins/dataset/rdf/sparql/ParallelEntityRetriever.scala, silk-plugins/silk-plugins-rdf/src/main/scala/org/silkframework/plugins/dataset/rdf/sparql/SimpleEntityRetriever.scala, silk-rules/src/main/scala/org/silkframework/rule/execution/CacheLoader.scala, silk-rules/src/main/scala/org/silkframework/rule/execution/local/LocalLinkSpecExecutor.scala, silk-workbench/silk-workbench-core/app/org/silkframework/runtime/users/WebUser.scala, silk-workbench/silk-workbench-workspace/app/controllers/workspace/ProjectMarshalingApi.scala, silk-workbench/silk-workbench-workspace/app/controllers/workspace/WorkspaceApi.scala, silk-workbench/silk-workbench-workspace/app/controllers/workspace/WorkspaceController.scala, silk-workspace/src/main/scala/org/silkframework/workspace/InMemoryWorkspaceProvider.scala, silk-workspace/src/main/scala/org/silkframework/workspace/Module.scala, silk-workspace/src/main/scala/org/silkframework/workspace/ProjectTask.scala, silk-workspace/src/main/scala/org/silkframework/workspace/Workspace.scala, silk-workspace/src/main/scala/org/silkframework/workspace/WorkspaceProvider.scala, silk-workspace/src/main/scala/org/silkframework/workspace/activity/ProjectActivity.scala, silk-workspace/src/main/scala/org/silkframework/workspace/activity/TaskActivity.scala, silk-workspace/src/main/scala/org/silkframework/workspace/activity/linking/ExecuteLinkingFactory.scala, silk-workspace/src/main/scala/org/silkframework/workspace/activity/workflow/WorkflowExecutor.scala, silk-workspace/src/main/scala/org/silkframework/workspace/xml/XmlWorkspaceProvider.scala, silk-workspace/src/test/scala/org/silkframework/workspace/WorkspaceProviderTestTrait.scala
- log all important workspace events
- log more information relating to SPARQL and graphstore retrieval and writing
- add project and task to activity log messages
=> Improve logging

silk-rules/src/main/scala/org/silkframework/rule/evaluation/DetailedIndexer.scala, silk-rules/src/main/scala/org/silkframework/rule/plugins/aggegrator/NegationAggregator.scala, silk-rules/src/main/scala/org/silkframework/rule/similarity/Aggregation.scala, silk-rules/src/main/scala/org/silkframework/rule/similarity/Aggregator.scala
- Always use the default index for the 'negate' aggregator
- Refactor index logic of aggregators
=> Fix 'negate' aggregator index

silk-core/src/main/scala/org/silkframework/dataset/rdf/SparqlEndpointEntityTable.scala, silk-core/src/main/scala/org/silkframework/dataset/rdf/SparqlParams.scala, silk-plugins/silk-plugins-rdf/src/main/scala/org/silkframework/plugins/dataset/rdf/datasets/SparqlDataset.scala, silk-plugins/silk-plugins-rdf/src/main/scala/org/silkframework/plugins/dataset/rdf/endpoint/RemoteSparqlEndpoint.scala, silk-plugins/silk-plugins-rdf/src/main/scala/org/silkframework/plugins/dataset/rdf/executors/LocalSparqlSelectExecutor.scala, silk-plugins/silk-plugins-rdf/src/main/scala/org/silkframework/plugins/dataset/rdf/sparql/SparqlSamplePathsCollector.scala, silk-plugins/silk-plugins-rdf/src/main/scala/org/silkframework/plugins/dataset/rdf/tasks/SparqlSelectCustomTask.scala, silk-plugins/silk-plugins-rdf/src/test/scala/org/silkframework/plugins/dataset/rdf/executors/LocalSparqlSelectExecutorTest.scala
limit execution of SPARQL queries in:
- SPARQL endpoint dataset
- SPARQL Select operator
=> SPARQL query timeout

silk-core/src/main/scala/org/silkframework/cache/FileEntityCache.scala, silk-core/src/main/scala/org/silkframework/cache/Partition.scala, silk-core/src/main/scala/org/silkframework/entity/Link.scala, silk-core/src/main/scala/org/silkframework/runtime/activity/ActivityExecution.scala, silk-core/src/main/scala/org/silkframework/runtime/activity/ActivityMonitor.scala, silk-learning/src/main/scala/org/silkframework/learning/active/linkselector/LinkSelectorHelper.scala, silk-learning/src/main/scala/org/silkframework/learning/active/poolgenerator/SimpleLinkPoolGenerator.scala, silk-learning/src/test/scala/org/silkframework/learning/active/linkselector/LinkSelectorTest.scala, silk-plugins/silk-serialization-json/src/main/scala/org/silkframework/serialization/json/LinkingSerializers.scala, silk-rules/src/main/scala/org/silkframework/rule/evaluation/DetailedLink.scala, silk-rules/src/main/scala/org/silkframework/rule/evaluation/ReferenceEntities.scala, silk-rules/src/main/scala/org/silkframework/rule/evaluation/ReferenceLinks.scala, silk-rules/src/main/scala/org/silkframework/rule/evaluation/ReferenceLinksReader.scala, silk-rules/src/main/scala/org/silkframework/rule/execution/ExecuteTransform.scala, silk-rules/src/main/scala/org/silkframework/rule/execution/GenerateLinks.scala, silk-rules/src/main/scala/org/silkframework/rule/execution/Matcher.scala, silk-rules/src/main/scala/org/silkframework/rule/execution/local/LocalTransformSpecExecutor.scala, silk-rules/src/main/scala/org/silkframework/rule/execution/local/TransformedEntities.scala, silk-workbench/silk-workbench-rules/app/controllers/linking/Learning.scala, silk-workbench/silk-workbench-rules/app/controllers/linking/LinkingTaskApi.scala, silk-workbench/silk-workbench-rules/app/controllers/linking/ReferenceLinksManager.scala, silk-workspace/src/main/scala/org/silkframework/workspace/activity/workflow/LocalWorkflowExecutor.scala
- Fixes memory leak in linking execution/evaluation
- Reduces memory foot print of linking execution/evaluation
=> Reduce memory foot print of linking execution

silk-plugins/silk-plugins-json/src/main/scala/org/silkframework/plugins/dataset/json/JsonSource.scala, silk-plugins/silk-plugins-json/src/main/scala/org/silkframework/plugins/dataset/json/JsonTraverser.scala
Generate stable URIs instead of random ones.
=> JsonSource: Generate stable URIs

silk-react-components/src/HierarchicalMapping/containers/MappingRule/ObjectRule/ObjectRule.jsx, silk-react-components/src/HierarchicalMapping/containers/MappingRule/ObjectRule/ObjectRuleForm.jsx, silk-react-components/src/HierarchicalMapping/containers/MappingRule/ValueRule/ValueRuleForm.jsx, silk-react-components/src/HierarchicalMapping/containers/MappingsTree.jsx, silk-react-components/src/HierarchicalMapping/containers/MappingsWorkview.jsx, silk-react-components/src/HierarchicalMapping/containers/RootMappingRule.jsx
=> Fixed: CmemWorkflowMapDataset Dataset Mapping should add mapping rules

silk-core/src/main/scala/org/silkframework/runtime/plugin/DistanceMeasureExampleValue.scala, silk-core/src/main/scala/org/silkframework/runtime/plugin/annotations/DistanceMeasureExample.java, silk-rules/src/test/scala/org/silkframework/rule/test/DistanceMeasureTest.scala
Improvements to DistanceMeasureTest
=> Improve distance measure test

silk-plugins/silk-plugins-csv/src/main/scala/org/silkframework/plugins/dataset/csv/CsvSource.scala, silk-plugins/silk-plugins-csv/src/test/scala/org/silkframework/plugins/dataset/csv/CsvSourceTest.scala
=> CSV Source: Respect limit

silk-core/src/main/scala/org/silkframework/runtime/resource/ResourceCache.scala, silk-core/src/test/scala/org/silkframework/runtime/resource/ResourceCacheTest.scala
Added ResourceCache to cache values loaded from file resources.
=> ResourceCache 

silk-core/src/main/scala/org/silkframework/runtime/serialization/StreamXmlFormat.scala, silk-core/src/test/scala/org/silkframework/runtime/serialization/TestXmlStreamEntities.scala, silk-rules/src/main/scala/org/silkframework/rule/evaluation/ReferenceEntities.scala, silk-rules/src/test/scala/org/silkframework/rule/evaluation/ReferenceEntitiesTest.scala, silk-workspace/src/main/scala/org/silkframework/workspace/activity/CachedActivity.scala, silk-workspace/src/main/scala/org/silkframework/workspace/activity/WorkspaceActivity.scala, silk-workspace/src/main/scala/org/silkframework/workspace/activity/dataset/TypesCache.scala, silk-workspace/src/main/scala/org/silkframework/workspace/activity/linking/LinkingPathsCache.scala, silk-workspace/src/main/scala/org/silkframework/workspace/activity/linking/ReferenceEntitiesCache.scala, silk-workspace/src/main/scala/org/silkframework/workspace/activity/transform/TransformPathsCache.scala, silk-workspace/src/main/scala/org/silkframework/workspace/activity/transform/VocabularyCache.scala, silk-workspace/src/test/scala/org/silkframework/workspace/activity/CachedActivityTest.scala
=> Caching fixes

silk-plugins/silk-plugins-xml/src/main/scala/org/silkframework/plugins/dataset/xml/XmlTraverser.scala, silk-plugins/silk-plugins-xml/src/test/resources/org/silkframework/plugins/dataset/xml/xmlEntities.xml, silk-plugins/silk-plugins-xml/src/test/scala/org/silkframework/plugins/dataset/xml/XmlSourceTestBase.scala
XML Dataset: Values that include HTML entities are not retrieved
=> XML Dataset: Values that include HTML entities are not retrieved

silk-workspace/src/test/scala/org/silkframework/workspace/resources/PerProjectResourceRepositoryTest.scala
- add tests for resource deletion via resource manager
=> Add tests for CMEM-3058

silk-core/src/main/resources/org/silkframework/LinkSpecificationLanguage.xsd, silk-rules/src/main/scala/org/silkframework/rule/DatasetSelection.scala, silk-workspace/src/test/scala/org/silkframework/workspace/WorkspaceProviderTestTrait.scala
=> Don't remove whitespace layout in linking/transform restriction field

silk-rules/src/main/scala/org/silkframework/rule/plugins/transformer/date/DateToTimestampTransformer.scala, silk-rules/src/main/scala/org/silkframework/rule/plugins/transformer/date/DateUnit.java, silk-rules/src/main/scala/org/silkframework/rule/plugins/transformer/date/NumberToDurationTransformer.scala, silk-rules/src/main/scala/org/silkframework/rule/plugins/transformer/date/TimestampToDateTransformer.scala, silk-rules/src/test/scala/org/silkframework/rule/plugins/transformer/date/DateToTimestampTransformerTest.scala, silk-workbench/silk-workbench-core/app/config/WorkbenchLinks.scala, silk-workbench/silk-workbench-core/app/controllers/util/PluginUsageCollector.scala, silk-workbench/silk-workbench-core/app/controllers/workspaceApi/coreApi/PluginApi.scala, silk-workbench/silk-workbench-core/conf/coreApi.routes, silk-workbench/silk-workbench-rules/test/controllers/transform/PeakTransformApiTest.scala, silk-workbench/silk-workbench-workflow/app/models/workflow/WorkflowConfig.scala, silk-workbench/silk-workbench-workflow/app/views/workflow/editor/dataset.scala.html, silk-workbench/silk-workbench-workflow/app/views/workflow/editor/operator.scala.html
The "Timestamp to date" and "Date to timestamp" transformers support configurable time units and full xsd:dateTime values.
=> Timestamp transformer improvements

silk-workspace/src/main/scala/org/silkframework/workspace/Project.scala, silk-workspace/src/main/scala/org/silkframework/workspace/ProjectTask.scala, silk-workspace/src/main/scala/org/silkframework/workspace/Workspace.scala, silk-workspace/src/test/scala/org/silkframework/workspace/WorkspaceTest.scala
On reloading the workspace, cancel any previously running task activity.
=> On reloading the workspace, cancel any previously running task activity.

silk-core/src/main/scala/org/silkframework/dataset/rdf/GraphStoreTrait.scala
…oGraph to improve reliability
=> Improve graph store POST reliability by using file upload internally

silk-core/src/main/scala/org/silkframework/config/Config.scala, silk-core/src/main/scala/org/silkframework/runtime/plugin/ParameterType.scala, silk-rules/src/main/scala/org/silkframework/rule/evaluation/Value.scala, silk-rules/src/test/scala/org/silkframework/rule/test/TransformerTest.scala, silk-workbench/silk-workbench-rules/app/views/evaluateTransform/generatedEntities.scala.html, silk-workbench/silk-workbench-rules/app/views/widgets/linksTable.scala.html
Improvements to transform error reporting
=> transform improvements

silk-core/src/main/scala/org/silkframework/config/Config.scala, silk-core/src/main/scala/org/silkframework/config/ConfigValue.scala, silk-core/src/main/scala/org/silkframework/runtime/plugin/PluginRegistry.scala, silk-core/src/test/scala/org/silkframework/config/ConfigTest.scala, silk-core/src/test/scala/org/silkframework/config/ConfigValueTest.scala, silk-core/src/test/scala/org/silkframework/runtime/plugin/PluginRegistryConfigTest.scala, silk-workbench/silk-workbench-core/app/controllers/core/ConfigController.scala
- The configuration of plugins (in particular the blacklist) has been improved
- Plugin configuration has been grouped under a common root
- Plugins can be enabled/disabled individually
=> Improved plugin configuration

silk-workbench/silk-workbench-workspace/app/controllers/workspace/DatasetApi.scala
DatasetAPI: Types endpoint should return an error, if the types cache failed to load
=> DatasetAPI: Types endpoint should return an error, if the types cache failed to load

silk-rules/src/main/scala/org/silkframework/rule/TransformRule.scala, silk-rules/src/test/scala/org/silkframework/rule/UriPatternTest.scala
- Fixed URI pattern parser if parsing patterns with no prefix.
- Added tests for URI pattern parser
=> Fixed URI pattern parser if parsing patterns with no prefix.

build.sbt, silk-core/src/main/scala/org/silkframework/runtime/serialization/StreamXmlFormat.scala, silk-plugins/silk-plugins-xml/src/main/scala/org/silkframework/plugins/dataset/xml/XmlSink.scala, silk-rules/src/main/scala/org/silkframework/rule/evaluation/ReferenceEntities.scala
- Fix build artifacts built with Java11, so they can run in Java8.
=> Fix Java 11 build

silk-plugins/silk-plugins-xml/src/main/scala/org/silkframework/plugins/dataset/xml/XmlSourceStreaming.scala, silk-plugins/silk-plugins-xml/src/test/scala/org/silkframework/plugins/dataset/xml/XmlSourceStreamingTest.scala
Fix: XML streaming did not comply to 'maxInMemorySize' config parameter when reading the currently processed entity into memory
=> XML streaming must comply to maxInMemorySize config parameter

silk-core/src/main/scala/org/silkframework/dataset/DatasetCharacteristics.scala, silk-core/src/main/scala/org/silkframework/dataset/rdf/RdfDataset.scala, silk-plugins/silk-plugins-json/src/main/scala/org/silkframework/plugins/dataset/json/JsonDataset.scala, silk-plugins/silk-plugins-xml/src/main/scala/org/silkframework/plugins/dataset/xml/XmlDataset.scala, silk-react-components/src/HierarchicalMapping/containers/MappingRule/ObjectRule/ObjectRuleForm.tsx, silk-react-components/src/HierarchicalMapping/containers/MappingRule/ValueRule/ValueRuleForm.tsx, silk-react-components/src/HierarchicalMapping/store.ts, silk-react-components/src/api/silkRestApi.ts, silk-workbench/silk-workbench-rules/app/controllers/transform/AutoCompletionApi.scala, silk-workbench/silk-workbench-rules/app/controllers/transform/autoCompletion/PartialSourcePathAutoCompletionRequest.scala, silk-workbench/silk-workbench-rules/app/controllers/transform/autoCompletion/PartialSourcePathAutocompletionHelper.scala, silk-workbench/silk-workbench-rules/test/controllers/transform/PartialAutoCompletionApiTest.scala, silk-workbench/silk-workbench-rules/test/controllers/transform/autoCompletion/PartialSourcePathAutoCompletionRequestTest.scala, silk-workbench/silk-workbench-rules/test/controllers/transform/autoCompletion/PartialSourcePathAutocompletionHelperTest.scala, workspace/src/app/views/pages/Linking/index.tsx, workspace/src/app/views/shared/RuleEditor/view/ruleNode/RuleNodeMenu.tsx
- Remove special paths from auto-completion for object mapping value path that would result in broken object mappings
=> Remove invalid special paths from auto completion

silk-core/src/main/scala/org/silkframework/entity/rdf/SparqlEntitySchema.scala, silk-plugins/silk-plugins-rdf/src/main/scala/org/silkframework/plugins/dataset/rdf/RdfFormatUtil.scala, silk-plugins/silk-plugins-rdf/src/test/scala/org/silkframework/plugins/dataset/rdf/RdfFormatUtilTest.scala
Reverts silk-framework/silk#549
=> Revert "Performance improvement: Replace FILTER IN with VALUES expression for entity list in SPARQL based datasets"

silk-core/src/main/scala/org/silkframework/entity/EntitySchema.scala, silk-workbench/silk-workbench-rules/app/controllers/linking/LinkingTaskApi.scala, silk-workspace/src/main/scala/org/silkframework/workspace/activity/linking/LinkingPathsCache.scala, workspace/src/app/views/shared/RuleEditor/contexts/RuleEditorEvaluationContext.tsx, workspace/src/app/views/shared/RuleEditor/model/RuleEditorModel.tsx, workspace/src/app/views/shared/RuleEditor/view/RuleEditorToolbar.tsx, workspace/src/app/views/taskViews/linking/evaluation/LinkingRuleEvaluation.tsx, workspace/src/locales/manual/en.json
- Linking paths cache did not update when linking rule is saved and contained yet uncached paths, e.g. multi-hop paths.
=> Fix linking paths cache path coverage

workspace/src/app/views/shared/FileUploader/cases/SelectFileFromExisting.tsx, workspace/src/app/views/shared/RuleEditor/model/RuleEditorModel.tsx, workspace/src/app/views/shared/RuleEditor/model/RuleEditorModel.utils.tsx, workspace/src/app/views/shared/RuleEditor/model/test/RuleEditorModel.utils.test.ts, workspace/src/app/views/shared/RuleEditor/view/ruleNode/RuleParameterInput.tsx, workspace/src/app/views/shared/RuleEditor/view/sidebar/SidebarSearchField.tsx, workspace/src/app/views/shared/modals/CreateArtefactModal/ArtefactForms/ParameterAutoCompletion.tsx, workspace/src/app/views/taskViews/linking/LinkingRuleEditor.tsx, yarn.lock
- Do not show linking task label in integrated view
=> Fix workflow/rule editor bugs

workspace/src/app/views/pages/MappingEditor/HierarchicalMapping/containers/MappingRule/ObjectRule/ObjectRuleForm.tsx, workspace/src/app/views/pages/MappingEditor/HierarchicalMapping/containers/MappingRule/ValueRule/ValueRuleForm.tsx, workspace/src/app/views/pages/MappingEditor/HierarchicalMapping/utils/wasTouched.js, workspace/src/app/views/taskViews/linking/activeLearning/config/ManualComparisonPairSelection.tsx, workspace/src/setupTests.ts
- used e.g. in mapping editor value path and URI template input
=> Improve auto suggestion component performance

silk-core/src/main/scala/org/silkframework/config/Prefixes.scala, silk-rules/src/main/scala/org/silkframework/rule/vocab/Vocabulary.scala, silk-workbench/silk-workbench-core/app/controllers/autoCompletion/Completions.scala, silk-workbench/silk-workbench-rules/app/controllers/linking/LinkingAutoCompletionApi.scala, silk-workbench/silk-workbench-rules/app/controllers/shared/autoCompletion/AutoCompletionApiUtils.scala, silk-workbench/silk-workbench-rules/app/controllers/transform/AutoCompletionApi.scala, silk-workbench/silk-workbench-rules/app/controllers/transform/autoCompletion/AutoSuggestAutoCompletionRequest.scala, silk-workbench/silk-workbench-rules/app/controllers/transform/autoCompletion/PartialSourcePathAutocompletionHelper.scala, silk-workbench/silk-workbench-rules/test/controllers/transform/PartialAutoCompletionApiTest.scala, silk-workbench/silk-workbench-workspace/app/controllers/workspace/WorkspaceApi.scala, silk-workbench/silk-workbench-workspace/app/controllers/workspace/doc/WorkspaceApiDoc.scala, silk-workbench/silk-workbench-workspace/app/controllers/workspaceApi/WorkspaceVocabularyApi.scala, silk-workbench/silk-workbench-workspace/conf/workspaceApi.routes, workspace/src/app/store/ducks/workspace/requests.ts, workspace/src/app/views/layout/Header/ExampleProjectImportMenu.tsx, workspace/src/app/views/pages/Linking/config/LinkageRuleConfig.tsx, workspace/src/app/views/pages/Linking/config/LinkageRuleConfigModal.tsx, workspace/src/app/views/pages/MappingEditor/HierarchicalMapping/components/AutoComplete.tsx, workspace/src/app/views/shared/autoCompletion/DefaultAutoCompleteField.tsx
- Add new endpoint to search for global vocabulary cache properties
=> Add auto-completion to link property in linkage rule config

workspace/src/app/views/pages/MappingEditor/HierarchicalMapping/HierarchicalMapping.jsx, workspace/src/app/views/pages/MappingEditor/HierarchicalMapping/components/AutoComplete.tsx, workspace/src/app/views/pages/MappingEditor/HierarchicalMapping/containers/MappingRule/ObjectRule/ObjectRuleForm.tsx, workspace/src/app/views/pages/MappingEditor/HierarchicalMapping/containers/MappingRule/ValueRule/ValueRuleForm.tsx, workspace/src/app/views/pages/MappingEditor/HierarchicalMapping/containers/RootMappingRule.jsx, workspace/src/app/views/pages/MappingEditor/HierarchicalMapping/elements/RuleTypes.jsx, workspace/src/app/views/pages/MappingEditor/HierarchicalMapping/utils/dataTypeUtils.ts
- Show value type label primarily instead of ID
=> Fix mapping editor bugs/issues

build.sbt, silk-core/src/main/scala/org/silkframework/dataset/VariableDataset.scala, silk-plugins/silk-serialization-json/src/main/scala/org/silkframework/serialization/json/JsonPluginModule.scala, silk-plugins/silk-serialization-json/src/main/scala/org/silkframework/serialization/json/WorkflowSerializers.scala, silk-plugins/silk-serialization-json/src/test/scala/JsonSerializersTest.scala, silk-plugins/silk-serialization-json/src/test/scala/org/silkframework/serialization/json/PluginSerializersTest.scala, silk-workbench/silk-workbench-workflow/app/controllers/workflowApi/variableWorkflow/VariableWorkflowRequestUtils.scala, silk-workbench/silk-workbench-workflow/app/controllers/workflowApi/workflow/WorkflowInfo.scala, silk-workbench/silk-workbench-workflow/app/org/silkframework/workbench/workflow/WorkflowWithPayloadExecutorFactory.scala, silk-workbench/silk-workbench-workflow/test/controllers/workflow/WorkflowClient.scala, silk-workbench/silk-workbench-workflow/test/controllers/workflowApi/SimpleVariableWorkflowApiTest.scala, silk-workbench/silk-workbench-workspace/app/controllers/util/ProjectUtils.scala, silk-workspace/src/main/scala/org/silkframework/workspace/activity/workflow/LocalWorkflowExecutor.scala, silk-workspace/src/main/scala/org/silkframework/workspace/activity/workflow/Workflow.scala, silk-workspace/src/main/scala/org/silkframework/workspace/activity/workflow/WorkflowExecutor.scala, silk-workspace/src/test/scala/org/silkframework/workspace/WorkspaceProviderTestTrait.scala, silk-workspace/src/test/scala/org/silkframework/workspace/activity/workflow/WorkflowTest.scala, workspace/src/app/views/shared/RuleEditor/view/RuleEditorCanvas.tsx, workspace/src/app/views/shared/RuleEditor/view/RuleEditorView.typings.ts, workspace/src/locales/manual/en.json
- replace the use of "variable dataset" tasks by allowing to mark datasets in a workflow to be variable.
=> Workflow editor support for variable datasets

workspace/src/app/views/shared/modals/CreateArtefactModal/ArtefactForms/ParameterAutoCompletion.tsx, workspace/src/app/views/shared/modals/CreateArtefactModal/ArtefactForms/ParameterWidget.tsx, workspace/src/app/views/shared/modals/CreateArtefactModal/ArtefactForms/TaskForm.tsx, workspace/src/app/views/shared/modals/CreateArtefactModal/CreateArtefactModal.tsx
- Did not work with default values
=> Fix dependent values auto-completion

workspace/src/app/views/layout/Header/KeyboardShortcutsModal.tsx, workspace/src/locales/manual/en.json
=> add help to the overview

silk-core/src/main/scala/org/silkframework/dataset/DatasetSpec.scala, silk-workbench/silk-workbench-workflow/app/controllers/workflowApi/WorkflowApi.scala, silk-workbench/silk-workbench-workspace/app/controllers/projectApi/ProjectTaskApi.scala, silk-workbench/silk-workbench-workspace/app/controllers/workspaceApi/SearchApi.scala, silk-workbench/silk-workbench-workspace/app/controllers/workspaceApi/projectTask/RelatedItem.scala, silk-workbench/silk-workbench-workspace/app/controllers/workspaceApi/search/DatasetFacetCollector.scala, silk-workbench/silk-workbench-workspace/app/controllers/workspaceApi/search/SearchApiModel.scala, silk-workbench/silk-workbench-workspace/test/controllers/workspace/SearchApiIntegrationTest.scala, workspace/src/app/store/ducks/shared/typings.ts, workspace/src/app/store/ducks/workspace/typings/IWorkspacePreview.ts, workspace/src/app/store/ducks/workspace/typings/index.ts, workspace/src/app/views/shared/RelatedItems/RelatedItem.tsx, workspace/src/app/views/shared/SearchList/SearchItem.tsx, workspace/src/app/views/shared/modals/RecentlyViewedModal.tsx, workspace/src/locales/manual/en.json
Added facet to filter datasets based on their access permissions.
=> Added facet to filter datasets based on their access permissions.

silk-workbench/silk-workbench-core/app/cacheUpdater/CacheUpdaterTask.scala, silk-workbench/silk-workbench-core/test/cacheUpdater/CacheUpdaterIntegrationTest.scala
- Move CacheUpdaterIntegrationTest to a module that's also included i…n eccenca DataIntegration.
- Fix CacheUpdaterIntegrationTest
=> Fix CacheUpdaterIntegrationTest

workspace/src/app/store/ducks/common/operations.ts, workspace/src/app/store/ducks/common/tests/operations.test.ts, workspace/src/app/views/pages/MappingEditor/HierarchicalMapping/containers/SuggestionNew/VocabularyMatchingDialog.tsx, workspace/src/app/views/plugins/plugin.types.ts, workspace/src/app/views/shared/RuleEditor/view/ruleNode/NodeContent.tsx, workspace/src/app/views/shared/RuleEditor/view/ruleNode/RuleNodeFormParameter.tsx, workspace/src/app/views/shared/RuleEditor/view/ruleNode/RuleNodeParameterForm.tsx, workspace/src/app/views/shared/RuleEditor/view/ruleNode/RuleParameterInput.tsx, workspace/src/app/views/shared/TaskConfig/TaskConfigPreview.tsx, workspace/src/app/views/shared/modals/CreateArtefactModal/ArtefactForms/ParameterAutoCompletion.tsx, workspace/src/app/views/shared/modals/CreateArtefactModal/ArtefactForms/ParameterWidget.tsx, workspace/src/app/views/shared/modals/CreateArtefactModal/ArtefactForms/TaskForm.tsx, workspace/src/app/views/shared/modals/CreateArtefactModal/CreateArtefactModal.tsx
- Do not disable depending input if dependent input has any default value
=> Fix various issues in the create/update dialog

workspace/src/app/hooks/useErrorHandler.tsx, workspace/src/app/views/shared/RuleEditor/RuleEditor.typings.ts, workspace/src/app/views/shared/RuleEditor/model/RuleEditorModel.tsx, workspace/src/app/views/shared/RuleEditor/view/RuleEditorNotifications.tsx, workspace/src/app/views/shared/RuleEditor/view/RuleEditorToolbar.tsx, workspace/src/app/views/shared/RuleEditor/view/ruleNode/RuleParameterInput.tsx, workspace/src/app/views/shared/RuleEditor/view/sidebar/RuleEditorOperatorSidebar.tsx, workspace/src/app/views/taskViews/linking/LinkingRuleEditor.tsx, workspace/src/app/views/taskViews/linking/evaluation/LinkingRuleEvaluation.tsx, workspace/src/app/views/taskViews/transform/TransformRuleEditor.tsx, workspace/src/app/views/taskViews/transform/evaluation/TransformRuleEvaluation.tsx
Only show errors triggered by rule component in rule notifications; do not show messages older than the last save
=> Fix rule editor notifications

workspace/src/app/views/shared/SampleError/SampleErrorModal.tsx, workspace/src/app/views/shared/modals/CreateArtefactModal/ArtefactForms/ArtefactFormParameter.tsx, workspace/src/app/views/taskViews/transform/transformEditor.utils.ts
fix for template field crashes on misformatted blocks
fix for rule evaluation does not show errors in path operators
=> pushed fix for breaking editor and rule operators and for rules not showing errors

workspace/src/app/views/pages/MappingEditor/HierarchicalMapping/containers/MappingRule/ObjectRule/ObjectRuleForm.tsx
- URI pattern auto-complete input sometimes resets to initial value or crashes the mapping editor
=> Fix: URI pattern input issues

silk-workspace/src/main/scala/org/silkframework/workspace/activity/workflow/LocalWorkflowExecutor.scala, silk-workspace/src/main/scala/org/silkframework/workspace/metrics/WorkspaceMetrics.scala
This PR adds the **project** as a tag to the project-specific and application-aware metrics of Prometheus using Micrometer. It also changes the "spec(ification)" to a "type", which may be less confusing for end users.
=> Slight Prometheus/Micrometer metric changes

workspace/src/app/views/shared/modals/CloneModal.tsx, workspace/src/app/views/shared/modals/CopyToModal/CopyToModal.tsx, workspace/src/app/views/shared/modals/DeleteModal.tsx
- Disable submit button during init
- Set loading state in submit button when pressed and working
=> Make item clone modal consistent with other modals
